# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Shandilya's Egress
email: saurabhshandilya.1991@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An async pipe & filter for internal noise
# url: "https://saurabhshandilya.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shadyshandilya
github_username:  beyondszine
linkedin_id: "shandilyasaurabh"

reading_time:     true
words_per_minute: 200


show_downloads: false
google_analytics: G-YWWL57GDH4
sass:
  sass_dir: _sass
  style: compressed


# Theme
# theme: jekyll-theme-potato-hacker                 # Uncomment this
# remote_theme: luxedo/jekyll-theme-potato-hacker   # Or this
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/avatar.jpg"
avatar_description: "My name is Saurabh Shandilya and I'm a tech junkie."
highlighter_theme: gruvbox  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - dropdown1
  - dropdown2
  - About

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true
# ------------------------------------------------------------------------------


# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed


# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Serving
# can get it from here: https://jekyllrb.com/docs/configuration/default/
detach              : false
port                : 4001
host                : 0.0.0.0
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : true
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : true
  strict_variables  : false


# additional variables
author: "saurabh shandilya"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# Build settings
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
